In [1]:
import numpy as np
import pickle
import os, sys
from keras.models import Model, load_model
import keras.backend as K

Using TensorFlow backend.


In [3]:
model = load_model('../models/emotion_recognition_model.hdf5')

In [4]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 50, 3125)          0         
_________________________________________________________________
bidirectional_1 (Bidirection (None, 50, 600)           8222400   
_________________________________________________________________
utter (Bidirectional)        (None, 600)               2162400   
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 3005      
Total params: 10,387,805
Trainable params: 10,387,805
Non-trainable params: 0
_________________________________________________________________


In [4]:
data_all = pickle.load(open("../models/data_word_id_map.pkl","rb"))
train_x, train_y, test_x, test_y, id2word, word2id = data_all[0], data_all[1], data_all[2], data_all[3], data_all[4], data_all[5]

In [5]:
def calc_test_result(pred_label, test_label):

    true_label = []
    predicted_label = []

    for i in range(pred_label.shape[0]):
        true_label.append(np.argmax(test_label[i]))
        predicted_label.append(np.argmax(pred_label[i]))
    print("Confusion Matrix :")
    print(confusion_matrix(true_label, predicted_label))
    print("Classification Report :")
    print(classification_report(true_label, predicted_label, digits=4))
    print('Weighted FScore: \n ', precision_recall_fscore_support(true_label, predicted_label, average='weighted'))

In [6]:
pred_test = model.predict(test_x)
pred_test

array([[8.0802664e-03, 1.3291232e-02, 9.4877529e-01, 1.8122118e-02,
        1.1731087e-02],
       [8.1682354e-01, 7.3865737e-04, 1.3790668e-03, 6.7953854e-03,
        1.7426334e-01],
       [1.3248883e-02, 7.8050566e-01, 2.6508944e-02, 7.3509254e-02,
        1.0622736e-01],
       ...,
       [5.4066600e-03, 9.1925013e-01, 1.2093944e-02, 2.6138881e-02,
        3.7110463e-02],
       [5.6953534e-02, 1.1969742e-02, 1.3387237e-03, 7.5016436e-03,
        9.2223632e-01],
       [2.5593489e-04, 9.8778665e-01, 2.3875968e-03, 4.5254924e-03,
        5.0444412e-03]], dtype=float32)

In [7]:
pred_test.shape

(1476, 5)

### angry- 0,   sad- 1,   happy- 2,   neutral- 3，frustrated- 4

## train set result

In [7]:
calc_test_result(pred_test, test_y)

Confusion Matrix :
[[125   2   3  31  59]
 [ 10 129  16  43  42]
 [ 21  17 220  58   8]
 [ 21  27  40 181  64]
 [ 35  29  24  74 197]]
Classification Report :
             precision    recall  f1-score   support

          0     0.5896    0.5682    0.5787       220
          1     0.6324    0.5375    0.5811       240
          2     0.7261    0.6790    0.7018       324
          3     0.4677    0.5435    0.5028       333
          4     0.5324    0.5487    0.5405       359

avg / total     0.5851    0.5772    0.5797      1476

Weighted FScore: 
  (0.5851061253771398, 0.5772357723577236, 0.5796714974045769, None)


In [7]:
calc_test_result(pred_test, test_y)

Confusion Matrix :
[[ 92   7   8  11 102]
 [  1 158  19  12  50]
 [  7  50 230  23  14]
 [ 10  58  48 132  85]
 [ 13  49  20  38 239]]
Classification Report :
             precision    recall  f1-score   support

          0     0.7480    0.4182    0.5364       220
          1     0.4907    0.6583    0.5623       240
          2     0.7077    0.7099    0.7088       324
          3     0.6111    0.3964    0.4809       333
          4     0.4878    0.6657    0.5630       359

avg / total     0.6031    0.5766    0.5724      1476

Weighted FScore: 
  (0.6031254810357016, 0.5765582655826558, 0.5724006538980043, None)


## test set result

In [8]:
pred_train = model.predict(train_x)
calc_test_result(pred_train, train_y)

Confusion Matrix :
[[ 665   13    7   50  148]
 [   7  675   22   75   65]
 [  10   24 1148  112   18]
 [  24   57   56 1148   90]
 [  85   36   23  160 1186]]
Classification Report :
             precision    recall  f1-score   support

          0     0.8407    0.7531    0.7945       883
          1     0.8385    0.7998    0.8187       844
          2     0.9140    0.8750    0.8941      1312
          3     0.7430    0.8349    0.7863      1375
          4     0.7870    0.7960    0.7915      1490

avg / total     0.8204    0.8167    0.8174      5904

Weighted FScore: 
  (0.8203820560460446, 0.8167344173441734, 0.817408988907042, None)


In [9]:
pred_train = model.predict(train_x)
calc_test_result(pred_train, train_y)

Confusion Matrix :
[[ 394   31   16   30  412]
 [   0  710   23   31   80]
 [   2  139 1114   31   26]
 [   9  195  152  862  157]
 [  39   95   33  104 1219]]
Classification Report :
             precision    recall  f1-score   support

          0     0.8874    0.4462    0.5938       883
          1     0.6068    0.8412    0.7051       844
          2     0.8326    0.8491    0.8408      1312
          3     0.8147    0.6269    0.7086      1375
          4     0.6436    0.8181    0.7204      1490

avg / total     0.7567    0.7282    0.7233      5904

Weighted FScore: 
  (0.756663594722732, 0.728150406504065, 0.7232840644052699, None)


## user input inference

In [5]:
# 去掉一些停用词
def filter_sent(sent):
    return sent.replace("'", ' ').replace('-', ' ').replace('.', ' ').replace('?', ' ').replace(':', ' ').replace(';', ' ').replace('(', ' ').replace(')', ' ').replace('!', ' ').replace('/', ' ')

In [6]:
def get_word_indices(data_x, MaxLen):
    length = len(data_x)
    word_list = []
    for word in data_x:
        if not word in word2id:
            # 遇到词汇表之外的词就把它归为unknown
            word_list.append(word2id['<UNK>'])
        else:
            word_list.append(word2id[word])
    return np.array(word_list + [0]*(MaxLen-length))[:MaxLen]

In [7]:
def get_one_hot(label, wordNum):
    label_arr = [0] * wordNum
    label_arr[label]=1
    return label_arr[:]

In [8]:
def expendToOneHot(x, wordNum, MaxLen):
    t = np.expand_dims(x, axis=2)
    t = t.tolist()
    for i in range(len(t)):
        for j in range(MaxLen):
            if(t[i][j][0] == 0):
                t[i][j:] = [[0] * wordNum] * (MaxLen - j)
                break
            else:
                t[i][j] = get_one_hot(t[i][j][0], wordNum)
    return np.array(t)

In [9]:
def processUserInput(userInputString):
    wordNum = len(id2word)
    MaxLen = 50
    # 转小写
    userInputString = userInputString.lower()
    # 按空格split成一个元素为word的list
    split_list = filter_sent(userInputString).split()
    # 将word按照word2id转为id
    sentence_word_indices = get_word_indices(split_list, MaxLen)
    # 扩展维度到合适的input维度（1×50×2811）
    sentence_word_indices = np.expand_dims(sentence_word_indices, axis=0)
    final_input = expendToOneHot(sentence_word_indices, wordNum, MaxLen)    
    return final_input

In [14]:
while True:
    sentence = input("Input a sentence: ")
    if sentence == 'exit':
        break
    userInput = processUserInput(sentence)
    
    res = model.predict(userInput).argmax()
    if(res == 0):
        res = 'angry'
    elif(res == 1):
        res = 'sad'
    elif(res == 2):
        res = 'happy'
    elif(res == 3):
        res = 'neutral'
    elif(res == 4):
        res = 'frustrated'

    print(res)

Input a sentence: i feel bad
sad
Input a sentence: are you sure
neutral
Input a sentence: you are bad
neutral
Input a sentence: i hate you
angry
Input a sentence: i want to sleep
frustrated
Input a sentence: yeah
neutral
Input a sentence: go away
frustrated
Input a sentence: done
sad
Input a sentence: it's over
sad
Input a sentence: OK
neutral
Input a sentence: I can't work out this problem!
frustrated
Input a sentence: I can't do it!
frustrated
Input a sentence: what are you talking about?
angry
Input a sentence: I am excited
happy
Input a sentence: exit
